server:
  port: 8081
spring:
  cloud:
    config:
      git:
        default-label: main
        uri: https://github.com/yerko-garces/config_data
        search-paths: config-data
application:
  name: config-service